.TH Guimup 1

.SH NAME
guimup \- a client for mpd

.SH SYNOPSIS
.B guimup

.SH DESCRIPTION
Guimup is a Client for MPD (the Music Player Daemon).

.SH OPTIONS
 -h(elp) 	   show an overview of these parameters
 -i(nstance)       force a new instance of the program
 -p(lay) %U        play files in list of uri
 -a(ppend) %U      append files in list of uri
  %U               default: append files in list of uri

.SH SEE ALSO
http://www.coonsden.com

.SH AUTHOR
Johan Spee / guimup@coonsden.com
