Document: guimup
Title: Debian guimup Manual
Author: <insert document author here>
Abstract: This manual describes what guimup is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/guimup/guimup.sgml.gz

Format: postscript
Files: /usr/share/doc/guimup/guimup.ps.gz

Format: text
Files: /usr/share/doc/guimup/guimup.text.gz

Format: HTML
Index: /usr/share/doc/guimup/html/index.html
Files: /usr/share/doc/guimup/html/*.html
